/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marcadministrationclient;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author patrice
 */
public class CreateTableJDialog extends javax.swing.JDialog
{

    String state = "Cancel";
    /**
     * Creates new form NewServerJFrame
     */
    public CreateTableJDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        CreateTablejPanel = new javax.swing.JPanel();
        TableNamejLabel = new javax.swing.JLabel();
        TableNamejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        CreateTablejButton = new javax.swing.JButton();
        CreateTablejButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        FieldsjTable = new javax.swing.JTable();
        AddAFieldTablejButton = new javax.swing.JButton();
        DeleteAFieldjButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Add a Server");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        CreateTablejPanel.setMaximumSize(new java.awt.Dimension(250, 210));
        CreateTablejPanel.setMinimumSize(new java.awt.Dimension(250, 210));
        CreateTablejPanel.setPreferredSize(new java.awt.Dimension(250, 210));
        CreateTablejPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                CreateTablejPanelComponentShown(evt);
            }
        });
        CreateTablejPanel.setLayout(new java.awt.GridBagLayout());

        TableNamejLabel.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        TableNamejLabel.setText("Table Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 16, 0, 0);
        CreateTablejPanel.add(TableNamejLabel, gridBagConstraints);

        TableNamejTextField.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 97;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 6);
        CreateTablejPanel.add(TableNamejTextField, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel3.setText("Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 16, 0, 0);
        CreateTablejPanel.add(jLabel3, gridBagConstraints);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Master", "Simple" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 0);
        CreateTablejPanel.add(jComboBox1, gridBagConstraints);

        CreateTablejButton.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        CreateTablejButton.setText("Create");
        CreateTablejButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CreateTablejButtonMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 16, 0, 0);
        CreateTablejPanel.add(CreateTablejButton, gridBagConstraints);

        CreateTablejButton1.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        CreateTablejButton1.setText("Kill");
        CreateTablejButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CreateTablejButton1MouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 36, 0, 0);
        CreateTablejPanel.add(CreateTablejButton1, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fields", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 9))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N

        FieldsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Type", "Size"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        FieldsjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                FieldsjTableMouseReleased(evt);
            }
        });
        jScrollPane12.setViewportView(FieldsjTable);

        AddAFieldTablejButton.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        AddAFieldTablejButton.setText("Add");
        AddAFieldTablejButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AddAFieldTablejButtonMouseReleased(evt);
            }
        });

        DeleteAFieldjButton.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        DeleteAFieldjButton.setText("Delete");
        DeleteAFieldjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DeleteAFieldjButtonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(AddAFieldTablejButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DeleteAFieldjButton))
            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteAFieldjButton)
                    .addComponent(AddAFieldTablejButton)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 38;
        gridBagConstraints.ipady = 126;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 16, 0, 6);
        CreateTablejPanel.add(jPanel2, gridBagConstraints);

        jButton1.setText("Ok");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CreateTablejPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CreateTablejPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String fields = "";
    public String name = "";
    MainJFrame _frame;
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        state = "Cancel";
        dispose();
    }//GEN-LAST:event_formWindowClosed

    private void CreateTablejButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateTablejButtonMouseReleased



        
        

    }//GEN-LAST:event_CreateTablejButtonMouseReleased

    private void CreateTablejButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateTablejButton1MouseReleased

        // delete a table


    }//GEN-LAST:event_CreateTablejButton1MouseReleased

    private void FieldsjTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldsjTableMouseReleased

        if ( evt.getButton() == java.awt.event.MouseEvent.BUTTON3)
        {
            AddAFieldTable();
        }
    }//GEN-LAST:event_FieldsjTableMouseReleased

    public void AddAFieldTable()
    {
            NewFieldJDialog d = new NewFieldJDialog();
            d.setModal(true);
            d.setLocationRelativeTo(FieldsjTable);
            d.setVisible(true);
            if ( d.state.equals("Ok") )
            {
                DefaultTableModel m = (DefaultTableModel) FieldsjTable.getModel();
                m.addRow(new String[] {d.NamejTextField.getText(),d.type,d.SizejTextField.getText()});
            }
    }
    private void AddAFieldTablejButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddAFieldTablejButtonMouseReleased

        this.AddAFieldTable();
    }//GEN-LAST:event_AddAFieldTablejButtonMouseReleased

        public void DeleteAFieldTable()
    {
        if ( FieldsjTable.getSelectedRow() == -1  )
        {
            return;
        }
        int numberOfrows = FieldsjTable.getSelectedRowCount();
        int row = -1;
        DefaultTableModel m = (DefaultTableModel) FieldsjTable.getModel();
        for (int i = 0; i < numberOfrows; i++)
        {
            row = FieldsjTable.getSelectedRows()[i];
            m.removeRow(row);
        }
    }
    private void DeleteAFieldjButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteAFieldjButtonMouseReleased

        DeleteAFieldTable();
    }//GEN-LAST:event_DeleteAFieldjButtonMouseReleased

    private void CreateTablejPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_CreateTablejPanelComponentShown

    }//GEN-LAST:event_CreateTablejPanelComponentShown

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        String fields = "";
        DefaultTableModel m = (DefaultTableModel) FieldsjTable.getModel();
        String type = "";
        for (int i = 0; i < m.getRowCount();i++)
        {
            type = (String) m.getValueAt(i, 1);
            fields += (String) m.getValueAt(i, 0)+" "+type;
            if ( type.equals("CHAR"))
            {
                fields += " "+(String) m.getValueAt(i, 2);
            }
            if ( i != m.getRowCount() - 1)
            {
                fields +=", ";
            }
        }
        this.name = this.TableNamejTextField.getText();
        this.fields = fields;
        this.state = "Ok";
        dispose();
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        state = "Cancel";
        dispose();
    }//GEN-LAST:event_jButton2MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateTableJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateTableJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateTableJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateTableJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateTableJDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAFieldTablejButton;
    private javax.swing.JButton CreateTablejButton;
    private javax.swing.JButton CreateTablejButton1;
    private javax.swing.JPanel CreateTablejPanel;
    private javax.swing.JButton DeleteAFieldjButton;
    private javax.swing.JTable FieldsjTable;
    private javax.swing.JLabel TableNamejLabel;
    private javax.swing.JTextField TableNamejTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane12;
    // End of variables declaration//GEN-END:variables
}
