/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marcadministrationclient;

/**
 *
 * @author patrice
 */
public class NewFieldJDialog extends javax.swing.JDialog 
{

    // codes des types de variables serveurs
    static String[] Sizes = {"3", "4", "1", "2", "6", "7", "9", "10", "5", "8", "12"};
        // Variables declaration - do not modify                     
    private javax.swing.JButton OkjButton;
    private javax.swing.JButton jButton1;
    public javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JTextField NamejTextField;
    public javax.swing.JTextField SizejTextField;
    // End of variables declaration   
    
    public String type;
       public String state = "Cancel";
    /**
     * Creates new form NewFieldJDialog
     */
    public NewFieldJDialog() 
    {
        initComponents();
        
    }

public static boolean isNumeric(String str)
{
    for (char c : str.toCharArray())
    {
        if (!Character.isDigit(c)) return false;
    }
    return true;
}
        private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) 
        {                                         
       
        String s = (String) jComboBox1.getSelectedItem();
        if ( !s.equals("CHAR") )
        {
            SizejTextField.setEnabled(false);
            SizejTextField.setText(Sizes[jComboBox1.getSelectedIndex()]);
        }
        else
        {
            SizejTextField.setEnabled(true);
            SizejTextField.setText("");
        }
    }     
        
    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) 
    {                                        
       
       if (  isNumeric( SizejTextField.getText() ) )
       {
           if ( Integer.parseInt(SizejTextField.getText()) > 255 )
           {
               SizejTextField.setText("255");
           }
           else
               if ( Integer.parseInt(SizejTextField.getText()) < 0 )
               {
                SizejTextField.setText("0");
               }
       }
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NamejTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        SizejTextField = new javax.swing.JTextField();
        
                SizejTextField.addKeyListener(new java.awt.event.KeyAdapter() 
                {
                    public void keyReleased(java.awt.event.KeyEvent evt) 
                    {
                        jTextField2KeyReleased(evt);
                    }
                }
                );
        
        OkjButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Add A New Field");

        jLabel1.setText("Name");

        jLabel2.setText("Type");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "INT8", "UINT8", "INT32", "UINT32", "INT64", "UINT64", "FLOAT", "DOUBLE", "CHAR", "STRING", "SIMPLEDATE" }));
        jComboBox1.setSelectedItem("CHAR");
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            @Override
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel3.setText("Size");


        OkjButton.setText("Ok");
        OkjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                OkjButtonMouseReleased(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(OkjButton)
                            .addGap(83, 83, 83)
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SizejTextField)
                                .addComponent(jComboBox1, 0, 167, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SizejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OkjButton)
                    .addComponent(jButton1)))
        );

        pack();
    }// </editor-fold>                        

    private void OkjButtonMouseReleased(java.awt.event.MouseEvent evt) {                                        
      state = "Ok";
      type = (String) this.jComboBox1.getSelectedItem();
      dispose();
    }                                       

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {                                       
     
        dispose();
    }                                      



                
}