/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marcadministrationclient;

import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Point;
import java.util.HashMap;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author patrice
 */
public class UpdateDataTableJDialogFutureUse extends JDialog
{

    String[][] texts;
    int lines,cols;
    String state = "Cancel";
    // correspondance entre checkbox et le contenu texte ligne i colonne j
    HashMap<JCheckBox,Integer[]> map;
    /**
     * Creates new form NewServerJFrame
     */
    public UpdateDataTableJDialogFutureUse(String[] fields) {
        this.map = new HashMap<>();
        initComponents();
        int i = 0; 
        for (String f : fields)
        {
            JCheckBox c = new JCheckBox(f);
            map.put(c, new Integer[]{i,i});
            c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCheckBoxMouseReleased(evt);
            }
        });
            this.UpdateDataTablejPanel.add(c);

        }
        revalidate();
        repaint();
        setModal(true);
    }

    private void jCheckBoxMouseReleased(java.awt.event.MouseEvent evt) {                                         

        if ( !(evt.getSource() instanceof JCheckBox) )
        {
            return;
        }
        JCheckBox theCheckBox = (JCheckBox) evt.getSource();
        String name = "textArea_"+theCheckBox.getText();
            // on checke qu'il n'est pas déjà affiché
        Component comp = this.FindTextAreaFromAccessibleName(this, name);
        if ( theCheckBox.isSelected() )
        {
            if ( comp == null )
            {
                javax.swing.JTextArea a = new javax.swing.JTextArea();
                a.getAccessibleContext().setAccessibleName("textArea_"+theCheckBox.getText());
                Point p = theCheckBox.getLocation();
                a.setLocation(p.x, p.y+50);
                a.setSize(new Dimension(608,120));
                this.add(a);
                this.revalidate();
                this.repaint();
            }
            else
            {
             ((JTextArea)comp).setEditable(true);
             comp.setEnabled(true);
            }

        }
        else
        {
            ((JTextArea)comp).setEditable(false);
            comp.setEnabled(false);
        }
        
    }     
    public Component FindTextAreaFromAccessibleName(Component comp, String name)  
{  
  if(comp instanceof JTextArea)  
  {  
    String accName = ((JTextArea) comp).getAccessibleContext().getAccessibleName();  
    if(accName.equals(name)) 
    {
        return comp;
    }  
  }  
  if (comp instanceof Container)  
  {  
    Component[] comps = ((Container)comp).getComponents();  
    for(int x = 0, y = comps.length; x < y; x++)  
    {  
      FindTextAreaFromAccessibleName(comps[x],name);  
    }  
  }  
  
  return null;
}  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        UpdateDataTablejPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea0 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Add a Server");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButton1.setText("Ok");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });

        UpdateDataTablejPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 0, 9))); // NOI18N
        UpdateDataTablejPanel.setMaximumSize(new java.awt.Dimension(250, 210));
        UpdateDataTablejPanel.setMinimumSize(new java.awt.Dimension(250, 210));
        UpdateDataTablejPanel.setPreferredSize(new java.awt.Dimension(250, 210));
        UpdateDataTablejPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                UpdateDataTablejPanelComponentShown(evt);
            }
        });

        jTextArea0.setColumns(20);
        jTextArea0.setRows(5);
        jScrollPane1.setViewportView(jTextArea0);

        javax.swing.GroupLayout UpdateDataTablejPanelLayout = new javax.swing.GroupLayout(UpdateDataTablejPanel);
        UpdateDataTablejPanel.setLayout(UpdateDataTablejPanelLayout);
        UpdateDataTablejPanelLayout.setHorizontalGroup(
            UpdateDataTablejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDataTablejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                .addContainerGap())
        );
        UpdateDataTablejPanelLayout.setVerticalGroup(
            UpdateDataTablejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDataTablejPanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(UpdateDataTablejPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String fields = "";
    public String name = "";
    MainJFrame _frame;
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        state = "Cancel";
        dispose();
    }//GEN-LAST:event_formWindowClosed

    private void UpdateDataTablejPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_UpdateDataTablejPanelComponentShown

    }//GEN-LAST:event_UpdateDataTablejPanelComponentShown

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        String fields = "";
        DefaultTableModel m = (DefaultTableModel) _frame.FieldsTable.getModel();
        String type = "";
        for (int i = 0; i < m.getRowCount();i++)
        {
            type = (String) m.getValueAt(i, 1);
            fields += (String) m.getValueAt(i, 0)+" "+type;
            if ( type.equals("CHAR"))
            {
                fields += " "+(String) m.getValueAt(i, 2);
            }
            if ( i != m.getRowCount() - 1)
            {
                fields +=", ";
            }
        }
       // this.name = this.TableNamejTextField.getText();
        this.fields = fields;
        this.state = "Ok";
        dispose();
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseReleased


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UpdateDataTablejPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea0;
    // End of variables declaration//GEN-END:variables
}
